redis:
    build: ./docker_images/redis
    restart: always
    hostname: redis.docker-example.net
    logging:
      options:
        max-size: 100m
        max-file: '3'
    networks:
      custom_react_network:
        ipv4_address: 172.16.238.4
        ipv6_address: 2001:3984:3989::4